export const SET_INITIAL_STATE = 'SET_INITIAL_STATE';
export const TOGGLE_ADD_CONTACT_MODAL = 'TOGGLE_ADD_CONTACT_MODAL';
export const CHANGE_CONTACTS_FORM_FIELD = 'CHANGE_CONTACTS_FORM_FIELD';
export const SUBMIT_CONTACTS_FORM = 'SUBMIT_CONTACTS_FORM';
export const FILTER_CONTACTS = 'FILTER_CONTACTS';
export const SORT_CONTACTS = 'SORT_CONTACTS';
